"""empty message

Revision ID: 3560703e48c9
Revises: 
Create Date: 2023-06-03 14:37:00.915845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3560703e48c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lahan_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=250), nullable=False),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengguna',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('terakhir_login', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('lahan',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.String(length=250), nullable=True),
    sa.Column('nama', sa.String(length=250), nullable=False),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.Column('luas', sa.Double(), nullable=False),
    sa.Column('alamat', sa.String(length=250), nullable=True),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lon', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lahan')
    op.drop_table('pengguna')
    op.drop_table('lahan_image')
    # ### end Alembic commands ###
